import type { ActivityEmail, CampaignSummary, DashboardData, EmailStatus } from '@/types/dashboard';

const icons: Record<string, string> = { queue: '▤', sent: '↗', rate: '◔' };
export function StatCard({ kind, label, value, detail, progress }: { kind: string; label: string; value: string; detail: string; progress?: number }) { return <article className="stat-card"><div className="stat-top"><span className={`stat-icon ${kind}`}>{icons[kind]}</span><span className="stat-label">{label}</span></div><strong>{value}</strong>{progress !== undefined ? <div className="progress-track"><span style={{ width: `${progress}%` }} /></div> : <div className="stat-detail"><span className="live-dot" />{detail}</div>}{progress !== undefined && <div className="stat-detail">{detail}</div>}</article>; }
function Status({ status }: { status: EmailStatus }) { return <span className={`status ${status}`}><i />{status === 'sent' ? 'Delivered' : status}</span>; }
export function Activity({ items }: { items: ActivityEmail[] }) { return <section id="activity" className="panel activity"><div className="panel-heading"><div><p className="kicker">Live feed</p><h2>Email activity</h2></div><span className="panel-count">{items.length} recent</span></div>{items.length ? <div className="activity-list">{items.map(item => <div className="activity-row" key={item.id}><span className="activity-avatar">{item.recipient.charAt(0).toUpperCase()}</span><div className="activity-copy"><strong>{item.recipient}</strong><span>{item.campaign.subject}</span></div><Status status={item.status} /><time>{new Date(item.sentAt ?? item.failedAt ?? item.scheduledTime).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</time></div>)}</div> : <Empty text="No email activity yet" />}</section>; }
export function SendingOverview({ volume, queuedFallback = 0 }: { volume: DashboardData['volumeByDay']; queuedFallback?: number }) { const safeVolume = Array.isArray(volume) ? volume : []; const sentTotal = safeVolume.reduce((sum, day) => sum + (Number(day.sent) || 0), 0); const plannedTotal = safeVolume.reduce((sum, day) => sum + (Number(day.planned) || 0), 0); const hasPlannedData = plannedTotal > 0; const showingPlanned = sentTotal === 0 && (hasPlannedData || queuedFallback > 0); const max = Math.max(...safeVolume.map(day => Number(showingPlanned ? day.planned : day.sent) || 0), queuedFallback, 1); const total = showingPlanned ? (hasPlannedData ? plannedTotal : queuedFallback) : sentTotal; const values = safeVolume.map((day, index) => ({ ...day, value: Number(showingPlanned ? day.planned : day.sent) || (showingPlanned && !hasPlannedData && index === safeVolume.length - 1 ? queuedFallback : 0) })); return <section className="panel overview"><div className="panel-heading"><div><p className="kicker">Last 7 days</p><h2>Sending overview</h2></div><span className="chart-total">{total} {showingPlanned ? 'planned' : 'sent'}</span></div><div className={`chart ${total === 0 ? 'chart-empty' : ''}`}>{values.length ? values.map(day => <div className="bar-column" key={day.date}><span className="bar-value">{day.value || ''}</span><div className="bar-track"><span aria-label={`${day.value} emails ${showingPlanned ? 'planned' : 'sent'} on ${day.date}`} style={{ height: `${day.value ? Math.max((day.value / max) * 100, 8) : 2}%` }} /></div><small>{day.label}</small></div>) : <p className="chart-empty-label">No sending data available</p>}{values.length > 0 && total === 0 && <p className="chart-empty-label">No sends in the last 7 days</p>}{showingPlanned && <p className="chart-note">Showing queued volume until sends are recorded</p>}</div></section>; }
export function QueueStatus({ queue }: { queue: DashboardData['queue'] }) { const items = [['Queued', queue.queued, 'queued'], ['Processing', queue.processing, 'processing'], ['Completed', queue.completed, 'completed'], ['Failed', queue.failed, 'failed']]; return <section className="panel queue-panel"><div className="panel-heading"><div><p className="kicker">Worker status</p><h2>Queue status</h2></div><span className="queue-live"><i />Live</span></div><div className="queue-list">{items.map(([label, value, kind]) => <div className="queue-item" key={kind}><span className={`queue-mark ${kind}`} /> <span>{label}</span><strong>{value}</strong></div>)}</div></section>; }
export function RecentCampaigns({ campaigns }: { campaigns: CampaignSummary[] }) { return <section id="scheduled" className="panel campaigns"><div className="panel-heading"><div><p className="kicker">Your latest work</p><h2>Recent campaigns</h2></div></div>{campaigns.length ? <div className="campaign-list">{campaigns.map(campaign => <div className="campaign-row" key={campaign.id}><div><strong>{campaign.subject}</strong><span>{campaign._count.emails} recipients</span></div><span className="campaign-time">{campaign.emails[0] ? new Date(campaign.emails[0].scheduledTime).toLocaleDateString() : 'Draft'}</span></div>)}</div> : <Empty text="No campaigns yet" />}</section>; }
function Empty({ text }: { text: string }) { return <div className="empty-small"><span>✦</span>{text}</div>; }
